name: smart_menu_app
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.17.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  fluentui_system_icons: ^1.1.178
  gap: ^2.0.0
  # Value equality
  equatable: ^2.0.5
  # Functional programming
  dartz: ^0.10.1
  get:
  # Inaternationalization
  flutter_localizations:
    sdk: flutter
  localization: ^2.1.0
  # Local cache
  shared_preferences: ^2.0.15
  # Remote API
  http: ^0.13.5
  internet_connection_checker: ^0.0.1+4
  # Bloc for state management
  flutter_bloc: ^8.1.1
  # service locator
  get_it: ^7.2.0
  # Load configuration at runtime from a .env file which can be used throughout the application
  flutter_dotenv: ^5.0.2
  cached_network_image: ^3.2.2
  flutter_slidable: ^2.0.0
  dotted_border: ^2.0.0+2
  intl: ^0.17.0
  badges: ^2.0.3
  flutter_barcode_scanner: ^2.0.0
  flutter_signin_button: ^2.0.0
  firebase_core: ^2.1.1
  firebase_auth: ^4.1.0
  google_sign_in: ^5.4.2
  flutter_vector_icons: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  mockito: ^5.3.0
  build_runner: ^2.2.0
  bloc_test: ^9.1.0

flutter:
  uses-material-design: true
  assets:
    - lib/i18n/
    - assets/
    - assets/icons/
    - assets/images/
