name: smart_menu_app
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.17.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  # Value equality
  equatable: ^2.0.5
  dartz: ^0.10.1
  fluentui_system_icons: ^1.1.178
  gap: ^2.0.0
  get:
  flutter_localizations:
    sdk: flutter
  localization: ^2.1.0
  internet_connection_checker: ^0.0.1+4
  shared_preferences: ^2.0.15

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  mockito: ^5.3.0
  build_runner: ^2.2.0

flutter:
  uses-material-design: true
  assets:
    - lib/i18n/
    - assets/
    - assets/icons/
